[package]
name = "turnstile-actions"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
borsh = "1.8.0"
bs58 = "0.5.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
solana-hash = { version = "4.6.0", features = ["serde"] }
solana-instruction = "3.5.0"
solana-message = { version = "4.5.0", features = ["serde"] }
solana-pubkey = { version = "4.3.0", features = ["curve25519", "serde"] }
solana-transaction = { version = "4.2.0", features = ["serde"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7.0", features = ["auth", "cors"] }
uuid = "1.24.0"
